apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: autoscaler-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       demo-app-vpa
  updatePolicy:
    # updateMode: "Off"
    updateMode: "Auto"
    # updateMode: "Initial"
    # updateMode: "Recreate"